#!/bin/bash
####################################################################################################
#
# ABOUT
#
#   Simple script to check to see if Firefox running.
#
####################################################################################################
#
# HISTORY
#
#   Version 1.0
#
####################################################################################################

IsFireFoxOn=$(pgrep firefox)
loggedInUser=$(ls -l /dev/console | awk '{print $3}')

if [[ $IsFireFoxOn != '' ]]; then
  echo "FIREFOX DETECTED"
  pkill -x firefox
  echo "FIREFOX KILLED"
  mv /Applications/Firefox.app /Users/$loggedInUser/.Trash
  echo "FIREFOX MOVED TO TRASH"
else
  echo "FIREFOX IS NOT RUNNING"
fi
